version: '3.1'
services:
  jira:
    restart: always
    container_name: jira
    image: ealebed/jira:7.5.0
    links:
      - database
    ports:
      - "8080:8080"
    environment:
      - "CATALINA_OPTS= -Xms768m -Xmx2536m"
    volumes:
      - /srv/jira:/var/atlassian/jira

  database:
    restart: on-failure
    container_name: mysql
    image: mysql/mysql-server:5.7

    environment:
      - MYSQL_DATABASE=jiradb
      - MYSQL_USER=jirauser
      - MYSQL_PASSWORD=jirapasswd
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - /srv/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    command:
      - '--collation-server=utf8_bin'
      - '--character-set-server=utf8'
      - '--max_allowed_packet=34M'
      - '--innodb_log_file_size=256M'

  nginx:
    restart: always
    container_name: nginx
    image: nginx:1.12-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf # or change ~/nginx/default.conf to fullpath
    links:
      - jira
